spring.application.name=Stocks_Demo
server.port=8063
spring.datasource.url=jdbc:h2:mem:portfolio_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret = q9xT2mL8vP4sK7nA1cD5fG8hJ3rW6yU0zB2eQ4tN7
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
finnhub.api.key=d7u7m19r01qvtsq0oij0d7u7m19r01qvtsq0oijg