<<<<<<< HEAD
spring.application.name=stocks-demo
server.port=8063
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_portfolio
spring.datasource.username=postgres
spring.datasource.password=1234
=======
spring.application.name=Stocks
server.port=8085
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/stocks_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
>>>>>>> f31afd343b5a1bc92cd50e1c5d73da5d87b5bd46

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

<<<<<<< HEAD
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

finnhub.api.key=d7u7m19r01qvtsq0oij0d7u7m19r01qvtsq0oijg
jwt.secret=q9xT2mL8vP4sK7nA1cD5fG8hJ3rW6yU0zB2eQ4tN7
=======
>>>>>>> f31afd343b5a1bc92cd50e1c5d73da5d87b5bd46
